# Site settings
title: Hatsukoi #website title
url: #https://kuoa.github.io # the base hostname & protocol for your site
baseurl: # the sub-path of your site, e.g. /blog/

disqus_shortname: # leave empty if you don't want comments
google_analytics: #if set to "true" modify the google_analytycs.html, set to false otherwise


# Links settings
links:
  - name:         Home
    url:          /
  - name:         Anime List
    url:          /anime-list
    external:     false
  - name:         About
    url:          /about
    external:     false
    external:     false
  - name:         aw
    url:          /anime/hunter-x-hunter
    external:     false

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
